[tasks.setupA]
script = '''
#!@deno
console.log("A done.");
'''
deno = { allow_net = [] }

[tasks.setupB]
script = '''
#!@deno
import { sleep } from "https://deno.land/x/sleep@v1.2.1/mod.ts";
console.log("B Extracting...");
await sleep(0.5);
console.log("B done.");
'''

[tasks.help]
depends = ["setupA", "setupB"]
script = '''
#!@deno
import { external } from "./external.ts";
import helloWorld from "npm:hello-world-npm";
console.log(`Files around ${import.meta.url}:`);
for (const entry of Deno.readDirSync(new URL(".", import.meta.url))) {
  console.log(` - ${entry.name}`);
}
external("module loaded.");
console.log(helloWorld.helloWorld());
console.log("Done!");
'''
deno = { allow_read = ["."] }
