[tasks.setupA]
script = '''
#!@deno
console.log("Dependencies: setupA done.");
'''

[tasks.setupB]
script = '''
#!@deno
console.log("Dependencies: setupB done.");
'''

[tasks.help]
depends = ["setupA", "setupB"]
script = '''
#!@deno
import { external } from "./external.ts";
console.log(`Files around ${import.meta.url}:`)
for (const entry of Deno.readDirSync(new URL(".", import.meta.url))) {
  console.log(` - ${entry.name}`);
}
external("module loaded.");
console.log("Done!");
'''

[tasks.help.deno]
allow_read = ["."]
