# Config file must be named 'rusk.toml', '.rusk.toml' or '*.rusk.toml' (glob pattern)

[tasks.main]
script = '''
echo 'sub1 & sub2 done'
'''
depends = ['sub1', 'sub2']

[tasks.sub1]
description = 'description 1'
depends = ['subsub']
script = '''
echo 'sub1 start'
sleep 2
echo 'sub1 done'
'''

[tasks.'sub2']
description = 'description 2'
depends = ['subsub']
script = '''
echo 'sub2 start'
sleep 1
echo 'sub2 done'
'''

[tasks.subsub]
script = '''
echo 'subsub called'
sleep 0.3
echo 'subsub done, then sub1&sub2 allowed to continue'
'''

# File-type tasks contains '.' or '/'
[tasks.'file.txt']
script = "touch file.txt"

# [tasks.'./Makefile']
