[tasks.all]
depends = ['single', 'async']

[tasks.single]
# depends = ['all'] # uncomment this line to see the error
script = "echo 'single start' && sleep 1.5 && echo 'single done'"

[tasks.async]
script = '''
echo 'sub1 & sub2 done'
'''
depends = ['sub1', 'sub2']

[tasks.sub1]
description = 'sub task 1'
depends = ['subsub']
script = '''
echo 'sub1 start'
sleep 2
echo 'sub1 done'
'''

[tasks.'sub2']
description = 'sub task 2'
depends = ['subsub']
script = '''
echo 'sub2 start'
sleep 1
echo 'sub2 done'
'''

[tasks.subsub]
script = '''
echo 'subsub called'
sleep 0.3
echo 'subsub done, then sub1&sub2 allowed to continue'
'''

[tasks.'/a']
depends = ['./hoge']
