[tasks.all]
script = "echo 'all done'"
depends = ['single', 'async']

[tasks.single]
script = "echo 'task1 start' && sleep 1.5 && echo 'task1 done'"

[tasks.async]
script = '''
echo 'sub1 & sub2 done'
'''
depends = ['sub1', 'sub2']

[tasks.sub1]
description = 'sub task 1'
script = '''
echo 'sub1 start'
sleep 2
echo '1 done'
'''

[tasks.'sub2']
description = 'sub task 2'
script = '''
echo 'sub2 start'
sleep 1
echo '2 done'
'''
