[tasks.task1]
description = 'task1 description'
script = '''
echo 'task1 start' && sleep 2 && echo 'task1 done'
'''

[tasks.'task2']
script = '''
echo 'task2 start' && sleep 1 && echo 'task2 done'
'''
depends = ['task1']
