[tasks.setupA]
deno = { allow_read = [], allow_run = [], allow_env = [], allow_sys = [] }
script = '''
#!@deno
import "npm:zx/globals";
await $`echo "A done."`;
'''

[tasks.setupB]
# depends = ["setupA"]
script = '''
#!@deno
import { sleep } from "https://deno.land/x/sleep@v1.2.1/mod.ts";
console.log("B Extracting...");
await sleep(0.5);
console.log("B done.");
'''

[tasks.help]
depends = ["setupA", "setupB"]
script = '''
#!@deno
import { external } from "./external.ts";
import { sleep } from "https://deno.land/x/sleep@v1.2.1/mod.ts";
console.log(`Files around ${import.meta.url}:`);
for (const entry of Deno.readDirSync(new URL(".", import.meta.url))) {
  console.log(` - ${entry.name}`);
}
external("module loaded.");
await sleep(0.5);
'''
deno = { allow_read = ["."] }
