[package]
name = "rusk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_runtime = "0.123.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_with = "3.2.0"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.44"
toml = "0.7.6"
