[package]
name = "rusk"
edition = "2021"
version = "0.1.0"

[dependencies]
deno_ast = { version = "0.27.3", features = ["transpiling"] }
deno_runtime = "0.122.0"
ignore = "0.4.20"
serde_with = "3.2.0"
thiserror = "1.0.44"
toml = "0.7.6"

[dependencies.serde]
version = "1.0.183"
features = ["std", "serde_derive"]
default-features = false

[dependencies.strum]
version = "0.25.0"
features = ["derive"]

[profile.release]
lto = true
panic = "abort"
strip = true

[profile.release.package]
