[tasks.setupA]
script = '''
#!@deno

console.log("setupA");
'''

[tasks.setupB]
script = '''
#!@deno

console.log("setupB");
'''

[tasks.help]
depends = ["setupA", "setupB"]
script = '''
#!@deno
import {external} from "./external.ts";
external();
console.log("Done!");
'''
