[tasks.aaa]
script = '''
#!@deno
const hello = "Task aaa";
console.log(hello);
'''

[tasks.keys]
script = '''
#!@deno
const hello = "Task keys";
console.log(hello);
'''

[tasks.help]
depends = ["keys", "aaa"]
script = '''
#!@deno
const hello = "Task help";
console.log(hello);
'''
